apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  template:
    spec:
      serviceAccountName: backstage
      volumes:
        - name: backstage-config
          projected:
            sources:
              - secret:
                  name: integrations
                  items:
                    - key: github-integration.yaml
                      path: github-integration.yaml
              - configMap:
                  name: backstage-config
                  items:
                    - key: app-config.yaml
                      path: app-config.yaml
              - secret:
                  name: k8s-config
                  items:
                    - key: k8s-config.yaml
                      path: k8s-config.yaml
      containers:
        - name: backstage
          image: ghcr.io/cnoe-io/backstage-app:9232d633b2698fffa6d0a73b715e06640d170162
          command:
            - node
            - packages/backend
            - --config
            - config/app-config.yaml
          volumeMounts:
            - name: backstage-config
              mountPath: "/app/config"
              readOnly: true
          envFrom:
            - secretRef:
                name: backstage-env-vars
