namespace: crossplane-system
resources:
  - https://github.com/awslabs/crossplane-on-eks/compositions/upbound-aws-provider/s3
  - resources/dynamodb/definition.yaml
  - resources/dynamodb/on-demand-composite-key.yaml